#!/bin/bash
# Run on osd node.
# ./db-block-devices.sh | sort -k2
# Example:
OSD     Block device    DB device
osd.14  /dev/sde        /dev/sda
osd.3   /dev/sdb        /dev/sda
osd.8   /dev/sdc        /dev/sda

my_data=$(ceph-volume lvm list | egrep "==== osd|devices|\[db\]|\[block\]" | sed 's/[block]].*//' | sed 's/\[bloc/block-device/g' | sed 's/\[d/db-device/g' | sed 's/devices//g' | sed 's/^ *//;s/ *$//;s/  */ /;')
osd_list=$(echo "$my_data"| grep osd | cut -d " " -f2)
#echo -e "OSD\tBLOCK\t\tDB"
printf "OSD\tBlock device\tDB device\n"
for OSD in $osd_list;do
  # Note to self: grep for osd's and add a space after, for uniqueness.
  XXX=$(echo "$my_data" | grep "$OSD\ " -A 4)
  YYY=$(echo "$XXX" | tail -n +2)
  DB=$(echo "$YYY" | grep "db-device" -A 1| tail -n +2)
  BLOCK=$(echo "$YYY" | grep "block-device" -A 1| tail -n +2)
  #echo -e "$OSD\t$BLOCK\t$DB"
  printf "%s\t%s\t%s\n" $OSD $BLOCK $DB
done
